---
version: "3.9"

services:

  bridge:
    build:
      dockerfile: Dockerfile
      context: .
    image: nyris/prometheus-grpc-bridge
    environment:
      GRPC_SERVER_CONNECT_ADDRESS: "example:11000"
      GRPC_SERVER_CONNECT_SCHEME: "http"
      HTTP_SERVER_LOG_STYLE: "simple"
    ports:
      - "8080:80"

  example:
    build:
      dockerfile: Dockerfile
      context: .
    image: nyris/prometheus-grpc-bridge
    entrypoint: prometheus-grpc-bridge-example
    ports:
      - "11000:11000"
